### ISSUE TITLE
Query regarding the structured auto-decoder

### ISSUE THREAD

**Issue by AvirupJU** [TaoHuUMD/StructLDM#4]
Hi,
Firstly, congrats for the amazing work!
I wanted to know how you performed the inverse skinning mentioned in Section 3.2. To my knowledge, there isn't any closed-form approach for it. It would be great if you provide some pseudo-code.

Thanks,
Avirup

**Comment by TaoHuUMD** [comment]
Hi Thanks for your interest. We used the same inverse skinning as [EVA3D](https://github.com/hongfz16/EVA3D) (Hong et al.). You can find the inverse skinning parts there.

**Comment by Sunyyyy** [comment]
已收到您的邮件！祝好~
