### ISSUE TITLE
batch_api函数无定义

### ISSUE THREAD

**Issue by dengdengf** [TaoHuUMD/StructLDM#5]
可以请问一下，为什么renderpeople文件里的test.sh文件中的最后这条语句 batch_api "${gpu}" "${cmd}" "test" "1380" ，其中batch_api这个函数没有定义呢？在其他文件中找不到这个定义

**Comment by Sunyyyy** [comment]
已收到您的邮件！祝好~

**Comment by TaoHuUMD** [comment]
Hi, you may try the new version.
