### ISSUE TITLE
A little question about Part-Aware Diffusion

### ISSUE THREAD

**Issue by CHMimilanlan** [TaoHuUMD/StructLDM#8]
Since I am new in this realm, there is a little question that I can't figure out.

I have carefully read the paper of this work, and I am confused about the Part-Aware Diffusion module, which is utilized to refine the latent UV Map after latent exchanged. Is the checkpoint of Part-Aware Diffusion model directly reused from the Structured Latent Diffusion Model, or retrained?

If the checkpoint of Part-Aware Diffusion model is reused from the Structured Latent Diffusion, my guess to the pipeline of Part-Aware Diffusion model is that, by inputting an exchanged latent UV Map, adding noise to it, and then using the Part-Aware Diffusion module to denoise it, we can get a refined latent UV Map. Is my guess correct?

I will be grateful for your timely response!

**Comment by TaoHuUMD** [comment]
It's correct. We trained one diffusion model for different tasks.

**Comment by CHMimilanlan** [comment]
Thanks !
